name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint code and run type checks
        run: pnpm run lint && pnpm run type-check

      - name: Check migrations for forbidden SQL
        run: pnpm run lint:sql

      - name: Run unit tests
        run: pnpm test -- --run
        continue-on-error: true

  cli-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build the CLI
        run: pnpm --filter @ozza/cli build

      - name: Run CLI --help to ensure it's executable
        run: node apps/cli/dist/index.js --help 